# Generated by Django 5.2.6 on 2026-02-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='capacity',
            new_name='sharing',
        ),
    ]
